### ISSUE TITLE
Get cannot get pyairmore to recognize an active session running in the foreground

### ISSUE THREAD

**Issue by rhvk37** [erayerdin/pyairmore#18]
Traceback (most recent call last):
  File "C:\Users\kfarr\Documents\workisboring", line 12, in <module>
    was_accepted = session.request_authorization()
  File "C:\Users\kfarr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyairmore\request\__init__.py", line 135, in request_authorization
    response = self.send(request, False)
  File "C:\Users\kfarr\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyairmore\request\__init__.py", line 154, in send
    raise ServerUnreachableException()
pyairmore.request.ServerUnreachableException: Server is found idle. The reasons might be:
- You might not even have installed Airmore to your device.
- Sometimes your Airmore server goes idle for battery saving. You need to open it up again.

**Comment by erayerdin** [comment]
Have you solved it?

**Comment by rhvk37** [comment]
It was a case of me being stupid and not seeing i had the wrong port lol im
trying to build a customer follow up script using your stuff. currently
working on getting the spread sheet to import. if something else comes up
ill let you know
