### ISSUE TITLE
Authorization request not received on Android.

### ISSUE THREAD

**Issue by ApurvaKunkulol** [erayerdin/pyairmore#2]
Traceback (most recent call last):
  File "C:\Users\apurva_kunkulol\Envs\nptel\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\apurva_kunkulol\Envs\nptel\lib\site-packages\urllib3\util\connection.py", line 79, in create_connection
    raise err
  File "C:\Users\apurva_kunkulol\Envs\nptel\lib\site-packages\urllib3\util\connection.py", line 69, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\apurva_kunkulol\Envs\nptel\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\apurva_kunkulol\Envs\nptel\lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "c:\python37\Lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\python37\Lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\python37\Lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\python37\Lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "c:\python37\Lib\http\client.py", line 956, in send
    self.connect()
  File "C:\Users\apurva_kunkulol\Envs\nptel\lib\site-packages\urllib3\connection.py", line 196, in connect
    conn = self._new_conn()
  File "C:\Users\apurva_kunkulol\Envs\nptel\lib\site-packages\urllib3\connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000234EBCD4828>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\apurva_kunkulol\Envs\nptel\lib\site-packages\requests\adapters.py", line 445, in send
    timeout=timeout
  File "C:\Users\apurva_kunkulol\Envs\nptel\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\apurva_kunkulol\Envs\nptel\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='xx.xx.xx.xx', port=2333): Max retries exceeded with url: /?Key=PhoneCheckAuthorization (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000234EBCD4828>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\apurva_kunkulol\Envs\nptel\lib\site-packages\pyairmore\request.py", line 20, in is_server_running
    response = self.post("/?Key=PhoneCheckAuthorization")
  File "C:\Users\apurva_kunkulol\Envs\nptel\lib\site-packages\requests\sessions.py", line 559, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\apurva_kunkulol\Envs\nptel\lib\site-packages\pyairmore\request.py", line 47, in request
    proxies, hooks, stream, verify, cert, json)
  File "C:\Users\apurva_kunkulol\Envs\nptel\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\apurva_kunkulol\Envs\nptel\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\apurva_kunkulol\Envs\nptel\lib\site-packages\requests\adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='xx.xx.xx.xx', port=2333): Max retries exceeded with url: /?Key=PhoneCheckAuthorization (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000234EBCD4828>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

**Comment by erayerdin** [comment]
Ah, sorry for the late response. It seems that I couldn't handle timeout properly. It seems like urllib could not have had any single response from the target device. That might be because:

 - *Airmore server on your device might not be running.* I've seen Airmore work differently under different Android versions. What I always do is, after I boot up my Android device, I ensure to open Airmore at least once (in order to get the server up and running) and keep it on front, not lock my device.
 - *Windows might have gotten into it." Some kinda firewall might have ruined it. Windows' security system asks if the application can connect to network when it is first opened up (first time you execute `python.exe`), you can check if you have given permission by seeing the properties of `python.exe`. Some custom firewalls and antivirus software might need a whitelist entry as well.
 - *Airmore server might be running on another port.* When Airmore tries to fire its server, it tries from 2333 and increment upwards if it cannot use that port. You can check your IP and port on top right of your Airmore application again.

Consider these and reply if you have further problems.

## Edit

By the way, can you connect your device on web browser?

**Comment by ApurvaKunkulol** [comment]
So I have to install, this on the phone too? 
What exactly, do I install on the phone(Android)?
By network you mean the regular data that a phone uses, right, or over the domestic WiFi.

Thanks.

**Comment by erayerdin** [comment]
@ApurvaKunkulol This library makes use of a popular Android application called "Airmore", which helps you manage you phone on computer by your browser and local network.

Of course, you need to download it to your phone from [Play Store](https://play.google.com/store/apps/details?id=com.airmore).

What this library does is, it makes use of Airmore application on your phone. I've naturally tested this library over a local network. Do these:

1. Download [Airmore](https://play.google.com/store/apps/details?id=com.airmore).
2. Open application.
3. Press top-right and press "Get IP".
4. Keep application open and screen lit.
5. Create `AirmoreSession` with your IP and port.
6. Run `session.is_server_running`.
7. If it is `True`, now you need to run `session.request_authorization()`.
8. Accept request on your phone.
9. Now you can do whatever you want.

And, please, read the [documentation](http://pyairmore.rtfd.io) to see what you can do after you create a session.

**Comment by ApurvaKunkulol** [comment]
@erayerdin: Thanks for the detailed description.
Apologies, because I didn't know about the application already, I ended up asking this. 
Still, Thanks for all this.
